### ISSUE TITLE
links on Templates page wrong

### ISSUE THREAD

**Issue by tczauderna** [sbgn/sbgn#6]
Many links on the Templates page (https://sbgn.github.io/sbgn/templates) to SVG, EPS, PDF, PNG etc. are wrong, e.g., ER L1 V2 PNG points to ER L1 V1.2.

**Comment by amazein** [comment]
I propose the page is updated and only the latest version is kept. We do not have to delete the other version but they could be made available somewhere at the end of the page. As Tobias suggested, should be corrected too. At the moment it is not clear who might be willing to do that. I am not familiar with the way the reference cards are created. Does not look like SBGN-ED. PowerPoint? Adobe Illustrator?

**Comment by fbergmann** [comment]
They were made with SBGN-ED in the past, reference cards are here: 

https://github.com/sbgn/libsbgn/tree/master/test-files

and from there exported  i would think. Someone else must have contributed the ppt. 

I don't see anything wrong with keeping other versions as well.

**Comment by tczauderna** [comment]
I'm not sure but I think the templates have been created and edited with Inkscape and then exported into the different formats (maybe except ppt).

I have only created examples and reference cards for libSBGN with SBGN-ED.

**Comment by amazein** [comment]
PPT for PD L1 V1.1: "404: Not Found"
PPT for ER L1 V1.0: cannot open this file
PPT for PD L1 V1.0: works, I know this one because I created this file a long time ago - by the way, this is not a reference card, not the same image, just a set of elements in PPT, should be removed from there.

Yes, we need to do something about the reference cards and templates, identify developers, have a way to reproduce. To minimise the work, I would focus only on the most recent versions, put everything else in some archive maybe.

So there are 
1) reference cards - the same image in different formats - I guess Inkscape is the source - probably there is a better way to create new reference cards; 
2) templates - could be SBGN-ED template, Newt template, Krayon template, PowerPoint template etc.

**Comment by amazein** [comment]
The original issue (wrong links) would be pretty easy to fix as soon as we have the original Inkscape files from which everything else was produced. This way reference cards would be in order.

**Comment by amazein** [comment]
ER L1 V1.0 Inkscape is missing
AF L1V1.2 files are missing except for PNG

**Comment by amazein** [comment]
The links are fixed
http://sbgn.github.io/sbgn/templates
Hanna has kindly agreed to recreate the missing AF L1V1.2 files

All the files are in this folder now:
http://sbgn.github.io/sbgn/templates

The old page is still there just in case:
http://sbgn.github.io/sbgn/templates_backup
https://github.com/sbgn/sbgn/blob/gh-pages/docs/templates_backup.md
